version: '3.8'

services:
  employers_bot:
    image: rb_employers_bot
    container_name: rb_employers_bot
    stop_signal: SIGINT
    build:
      context: ./employers_bot
    working_dir: "/usr/src/employers_bot/employers_bot"
    volumes:
    - .:/usr/src/employers_bot
    command: python3 -m bot
    restart: always
    env_file:
      - "employers_bot/.env"
    depends_on:
      - app


  app:
    image: rb_api
    build:
      context: ./api
    container_name: rb_api
    env_file:
      - api/.env
    # Если не работает эта команда, используйте закомментированную
    command: sh -c "gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - "8000:8000"
